# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='Reg_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
