# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190501_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='Reg_date',
        ),
        migrations.AlterField(
            model_name='c_details',
            name='C_Ph_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='Contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='d_details',
            name='D_Ph_no',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
