# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190502_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_details',
            name='C_Password',
        ),
        migrations.RemoveField(
            model_name='c_details',
            name='C_Username',
        ),
    ]
