# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190503_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Name', models.CharField(max_length=200)),
                ('D_Address', models.CharField(max_length=200)),
                ('D_Ph_no', models.CharField(max_length=10)),
                ('Truck_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='c_details',
            name='C_D_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.DriverInfo'),
        ),
        migrations.AlterField(
            model_name='trashcan1',
            name='T_D_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.DriverInfo'),
        ),
        migrations.DeleteModel(
            name='D_Details',
        ),
    ]
