# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190503_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_details',
            old_name='D_Address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='d_details',
            old_name='D_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='d_details',
            old_name='D_Ph_no',
            new_name='Ph_no',
        ),
    ]
